kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: sighup/kubeprimer-web
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_HOST
          value: backend-service
        - name: COMPANY
          value: Green Heroes
        - name: SOME_PASSWORD
          value: mysecret
